const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "94742876482"
const SESSION_ID = "PRABATH-MD~JCk1UYhQ#w2keUIbhVLu7huPx2tdtUOD2xf87fDFxsPtmrfboa6g"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
